FROM jenkins/jenkins:lts
ARG curl_user
ARG curl_proxy
USER root

# add jenkins user
RUN mkdir /home/jenkins && chown jenkins:jenkins /home/jenkins \
&& usermod -d /home/jenkins jenkins \
&& : "~/.bashrcにproxy設定する" \
&& : echo "export http_proxy=${http_proxy}" \
&& { echo "export http_proxy=${http_proxy}"; \
    echo "export https_proxy=${https_proxy}"; \
} | tee -a ~/.bashrc \
&& : "~/.curlrcにproxy設定する" \
&& : echo "proxy-user=${curl_user}" \
&& { echo "proxy-user=${curl_user}"; \
    echo "proxy=${curl_proxy}"; \
} | tee -a ~/.curlrc \
&& ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# install docker, docker-compose
ENV DOCKER_VERSION 18.09.1
ENV JAVA_OPTS=-Duser.timezone=Asia/Tokyo

RUN curl -fL -o docker.tgz "https://download.docker.com/linux/static/test/x86_64/docker-$DOCKER_VERSION.tgz" && \
    tar --strip-component=1 -xvaf docker.tgz -C /usr/bin

RUN curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

# USER jenkins